spring:
  profiles:
    active: mysql
  application:
    name: stoblyx
  # JPA 설정 추가
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 서버 포트 설정
server:
  port: 8080

# KoBART API 설정
kobart:
  enabled: ${KOBART_ENABLED:true}
  api:
    url: ${KOBART_API_URL:http://localhost:5000}
