# This is a dummy change to trigger GitHub Actions

spring:
  application:
    name: stoblyx-portfolio

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.219.101:3306/stoblyx_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 6188

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: 5468576D5A7134743777217A25432A462D4A614E645267556B58703272357538
  token-validity-in-seconds: 86400 # 24시간
