spring:
  profiles:
    active: development
  application:
    name: stoblyx

  # RabbitMQ 자동 설정 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:stoblyx_db}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:stoblyx_user}
    password: ${DB_PASSWORD:6188}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      connection-timeout: 20000
      validation-timeout: 5000
      max-lifetime: 1200000
      auto-commit: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: utf8
          charSet: UTF-8
          useUnicode: true

  data:
    redis:
      enabled: false
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  rabbitmq:
    enabled: ${RABBITMQ_ENABLED:false}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

jwt:
  # JWT 시크릿 키 (환경 변수에서 가져옴, 기본값은 개발 환경용)
  secret: ${JWT_SECRET:dev_jwt_secret_key_do_not_use_in_production} # 개발 환경용 기본값 추가
  # 액세스 토큰 만료 시간 (초 단위, 기본값 30분)
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_EXPIRATION:1800}
  # 리프레시 토큰 만료 시간 (초 단위, 기본값 7일)
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}

# 프로파일별 설정
---
spring:
  config:
    activate:
      on-profile: production

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: development

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080
  servlet:
    context-path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

kobart:
  api:
    url: http://localhost:5000 # Flask 서버 URL

logging:
  level:
    org.springframework.security: TRACE
    com.j30n.stoblyx: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.security.web.FilterChainProxy: DEBUG
    org.springframework.security.web.access: TRACE
