spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-hostname}:${DB_PORT:3306}/${DB_NAME:db_name}?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:username}
    password: ${DB_PASSWORD:password}
  # 다른 설정들...

jwt:
  secret: ${JWT_SECRET:your_jwt_secret}
  # 다른 JWT 설정...

# 기타 다른 설정들...