= Stoblyx API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
== 개요

Stoblyx API는 AI 기반 독서 요약 숏폼 플랫폼의 RESTful API입니다.

[[overview-http-verbs]]
=== HTTP 동사

본 API에서 사용하는 HTTP 동사(verbs)는 가능한한 REST 규약을 따릅니다.

[cols="20,80"]
|===
| 동사 | 용례

| `GET`
| 리소스를 조회할 때 사용

| `POST`
| 새 리소스를 생성할 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 때 사용
|===

[[overview-http-status-codes]]
=== HTTP 상태 코드

본 API에서 사용하는 HTTP 상태 코드는 가능한한 REST 규약을 따릅니다.

[cols="20,80"]
|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함

| `204 No Content`
| 기존 리소스를 성공적으로 삭제함

| `400 Bad Request`
| 잘못된 요청을 보낸 경우

| `401 Unauthorized`
| 인증되지 않은 사용자가 보호된 리소스에 접근하는 경우

| `403 Forbidden`
| 인증된 사용자가 권한이 없는 리소스에 접근하는 경우

| `404 Not Found`
| 요청한 리소스가 존재하지 않는 경우

| `500 Internal Server Error`
| 서버에 오류가 발생한 경우
|===

[[resources]]
== API 리소스

[[resources-auth]]
=== 인증 API

[[resources-auth-signup]]
==== 회원가입

operation::auth-signup[snippets='http-request,request-fields,http-response,response-fields']

[[resources-auth-login]]
==== 로그인

operation::auth-login[snippets='http-request,request-fields,http-response,response-fields']

[[resources-auth-refresh]]
==== 토큰 갱신

operation::auth-refresh[snippets='http-request,http-response,response-fields']

[[resources-auth-logout]]
==== 로그아웃

operation::auth-logout[snippets='http-request,http-response']

[[resources-quotes]]
=== 문구 API

[[resources-quotes-create]]
==== 문구 등록

operation::create-quote[snippets='http-request,request-fields,http-response,response-fields']

[[resources-quotes-get]]
==== 문구 조회

operation::get-quote[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-quotes-list]]
==== 문구 목록 조회

operation::get-quotes[snippets='http-request,query-parameters,http-response,response-fields']

[[resources-quotes-update]]
==== 문구 수정

operation::update-quote[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[resources-quotes-delete]]
==== 문구 삭제

operation::delete-quote[snippets='http-request,path-parameters,http-response']

[[resources-users]]
=== 사용자 API

[[resources-users-profile]]
==== 프로필 조회

operation::get-profile[snippets='http-request,http-response,response-fields']

[[resources-users-update]]
==== 프로필 수정

operation::update-profile[snippets='http-request,request-fields,http-response,response-fields']

[[resources-users-interests]]
==== 관심사 설정

operation::update-interests[snippets='http-request,request-fields,http-response,response-fields']

[[resources-comments]]
=== 댓글 API

[[resources-comments-create]]
==== 댓글 작성

operation::create-comment[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[resources-comments-get]]
==== 댓글 조회

operation::get-comment[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-comments-list-by-quote]]
==== 문구별 댓글 목록 조회

operation::get-comments-by-quote[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-comments-list-by-user]]
==== 사용자별 댓글 목록 조회

operation::get-comments-by-user[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-comments-update]]
==== 댓글 수정

operation::update-comment[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[resources-comments-delete]]
==== 댓글 삭제

operation::delete-comment[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-likes]]
=== 좋아요 API

[[resources-likes-like]]
==== 문구 좋아요

operation::like-quote[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-likes-unlike]]
==== 문구 좋아요 취소

operation::unlike-quote[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-likes-status]]
==== 문구 좋아요 상태 확인

operation::check-like-status[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-likes-list]]
==== 좋아요한 문구 목록 조회

operation::get-liked-quotes[snippets='http-request,http-response,response-fields']

[[resources-videos]]
=== AI 영상 API

[[resources-videos-generate]]
==== 영상 생성 요청

operation::generate-video[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[resources-videos-status]]
==== 영상 생성 상태 조회

operation::get-video-status[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-saved-quotes]]
=== 저장된 문구 API

[[resources-saved-quotes-save]]
==== 문구 저장

operation::save-quote[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-saved-quotes-list]]
==== 저장된 문구 목록 조회

operation::get-saved-quotes[snippets='http-request,http-response,response-fields']

[[resources-saved-quotes-remove]]
==== 저장된 문구 삭제

operation::remove-saved-quote[snippets='http-request,path-parameters,http-response']