name: API-테스트-자동화

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch: # 수동으로 워크플로우 실행 가능

jobs:
  test:
    name: API 테스트 실행
    runs-on: ubuntu-latest

    services:
      # MySQL 서비스 컨테이너
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 6188
          MYSQL_DATABASE: stoblyx_db
          MYSQL_USER: stoblyx_user
          MYSQL_PASSWORD: 6188
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      # Redis 서비스 컨테이너
      redis:
        image: redis:6.2
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 권한 설정
        run: chmod +x ./gradlew

      - name: Gradle 상태 확인
        run: |
          ./gradlew --version
          ./gradlew tasks --all

      - name: 환경 변수 설정
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/stoblyx_db" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=stoblyx_user" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=6188" >> $GITHUB_ENV
          echo "SPRING_REDIS_HOST=localhost" >> $GITHUB_ENV
          echo "SPRING_REDIS_PORT=6379" >> $GITHUB_ENV
          # 필요한 다른 환경 변수들도 여기에 추가

      - name: 테스트 실행
        run: |
          # 테스트 실행 전 환경 확인
          echo "=== 환경 변수 확인 ==="
          env | grep SPRING

          # 테스트 실행 (실패해도 계속 진행)
          ./gradlew test --info --stacktrace || true

          # 테스트 결과 확인
          echo "=== 테스트 결과 디렉토리 확인 ==="
          find build -name "*.xml" -o -name "*.html" | grep -v "/tmp/" | sort

      # 테스트 결과 상세 확인
      - name: 테스트 결과 확인
        run: |
          echo "=== 테스트 결과 상세 확인 ==="
          if [ -d "build/test-results/test" ]; then
            echo "테스트 결과가 생성되었습니다."
            ls -la build/test-results/test/
            
            # XML 결과 파일 내용 확인 (첫 번째 파일만)
            TEST_XML=$(find build/test-results/test -name "TEST-*.xml" | head -n 1)
            if [ -n "$TEST_XML" ]; then
              echo "=== 테스트 결과 샘플 ($TEST_XML) ==="
              cat "$TEST_XML" | head -n 30
            fi
          else
            echo "테스트 결과 디렉토리가 없습니다."
            # 빌드 디렉토리 구조 확인
            find build -type d | sort
          fi

      # 아티팩트 준비
      - name: 아티팩트 준비
        run: |
          # 테스트 결과 디렉토리 생성
          mkdir -p test-artifacts

          # 테스트 결과 복사 (있는 경우만)
          if [ -d "build/reports/tests/test" ]; then
            cp -r build/reports/tests/test test-artifacts/test-reports
          fi

          # 커버리지 결과 복사 (있는 경우만)
          if [ -d "build/reports/jacoco/test/html" ]; then
            cp -r build/reports/jacoco/test/html test-artifacts/coverage-reports
          fi

          # 테스트 결과 XML 복사 (있는 경우만)
          if [ -d "build/test-results/test" ]; then
            cp -r build/test-results/test test-artifacts/test-results
          fi

          # 디렉토리 내용 확인
          echo "=== 아티팩트 디렉토리 내용 ==="
          find test-artifacts -type f | sort

      # 아티팩트 업로드
      - name: 아티팩트 업로드
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts
          path: test-artifacts
