name: 테스트-보고서-게시

on:
  workflow_run:
    workflows: ["REST-Assured-API-테스트"]
    types:
      - completed

jobs:
  publish:
    name: 테스트 보고서 게시
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}

    # 권한 설정
    permissions:
      contents: write

    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: rest-assured-test-results
          path: artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: 아티팩트 디버깅
        run: |
          echo "워크플로우 실행 ID: ${{ github.event.workflow_run.id }}"
          echo "아티팩트 디렉토리 내용:"
          ls -la artifacts || echo "아티팩트 디렉토리가 없습니다"
          find artifacts -type f 2>/dev/null || echo "아티팩트 파일이 없습니다"

      - name: 보고서 준비
        run: |
          # 보고서 디렉토리 생성
          mkdir -p reports

          # 테스트 보고서 복사 (있는 경우만)
          if [ -d "artifacts/junit-reports" ]; then
            mkdir -p reports/unit-tests
            cp -r artifacts/junit-reports/* reports/unit-tests/
          fi

          # ExtentReports 복사 (있는 경우만)
          if [ -d "artifacts/extent-reports" ]; then
            mkdir -p reports/extent-reports
            cp -r artifacts/extent-reports/* reports/extent-reports/
          fi

          # 기본 인덱스 페이지 생성
          cat > reports/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="ko">
          <head>
            <meta charset="UTF-8">
            <title>API 테스트 보고서</title>
            <style>
              body { font-family: Arial, sans-serif; margin: 20px; }
              h1 { color: #2c3e50; }
              .report-link { display: block; margin: 10px 0; padding: 10px; background: #f5f5f5; }
            </style>
          </head>
          <body>
            <h1>API 테스트 보고서</h1>
            <a class="report-link" href="./unit-tests/index.html">JUnit 테스트 보고서</a>
            <a class="report-link" href="./extent-reports/extent-report.html">API 요청/응답 상세 보고서</a>
            <p>생성 시간: <span id="date"></span></p>
            <script>document.getElementById('date').textContent = new Date().toLocaleString();</script>
          </body>
          </html>
          EOF

          # 보고서 디렉토리 내용 확인
          echo "보고서 디렉토리 내용:"
          ls -la reports
          find reports -type f

      - name: GitHub Pages 배포
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: reports
          branch: gh-pages
          clean: true
