name: Slack 알림

on:
  workflow_run:
    workflows: ["API 테스트 자동화", "API 통합 테스트"]
    types:
      - completed

jobs:
  slack-notification:
    name: Slack 알림 전송
    runs-on: ubuntu-latest

    steps:
      - name: 워크플로우 상태 확인
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            echo "status=성공 :white_check_mark:" >> $GITHUB_OUTPUT
            echo "color=#2ecc71" >> $GITHUB_OUTPUT
          else
            echo "status=실패 :x:" >> $GITHUB_OUTPUT
            echo "color=#e74c3c" >> $GITHUB_OUTPUT
          fi

      - name: Slack 알림 전송
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,repo,message,commit,author,action,eventName,ref,job
          custom_payload: |
            {
              "attachments": [
                {
                  "color": "${{ steps.check.outputs.color }}",
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "${{ github.event.workflow_run.name }} 테스트 ${{ steps.check.outputs.status }}",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*저장소:*\n${{ github.repository }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*브랜치:*\n${{ github.event.workflow_run.head_branch }}"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*커밋:*\n${{ github.event.workflow_run.head_commit.message }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*작성자:*\n${{ github.event.workflow_run.head_commit.author.name }}"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*워크플로우:*\n${{ github.event.workflow_run.name }}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*실행 시간:*\n${{ github.event.workflow_run.updated_at }}"
                        }
                      ]
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "워크플로우 확인",
                            "emoji": true
                          },
                          "url": "${{ github.event.workflow_run.html_url }}"
                        },
                        {
                          "type": "button",
                          "text": {
                            "type": "plain_text",
                            "text": "테스트 보고서",
                            "emoji": true
                          },
                          "url": "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
                        }
                      ]
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
