name: Slack 알림 (비활성화됨)

# 이 워크플로우는 비활성화되었습니다.
# Slack 알림이 필요하지 않아 트리거를 제거했습니다.

on:
  # 어떤 이벤트에도 반응하지 않도록 설정
  workflow_dispatch: # 수동 실행만 가능하도록 설정

jobs:
  slack-notification:
    name: Slack 알림 전송 (비활성화됨)
    runs-on: ubuntu-latest
    # 항상 건너뛰도록 설정
    if: ${{ false }}

    steps:
      - name: 알림
        run: echo "이 워크플로우는 비활성화되었습니다."
