name: 아티팩트-테스트

on:
  workflow_dispatch:

jobs:
  upload-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          mkdir -p test-dir
          echo "This is a test file" > test-dir/test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test-dir
          retention-days: 1
